import {Poppins} from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'

const poppins = Poppins({
  weight: ['400', '100'],
  subsets: ['latin']
})
export const metadata = {
  title: 'Next app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
          <Navbar />
          <div className='container'>
              {children}
          </div>
      </body>
    </html>
  )
}
